# Generated by Django 4.1.1 on 2022-11-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pvchat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='Message',
            new_name='message',
        ),
    ]
